### PR TITLE
fix: camelCase prop names for Cal icon

### PR DESCRIPTION
**Pull request by rogervera**
Minor fix to clear error due to hyphenated attributes on the Cal icon

### CODE REVIEW

**Review by jackrr — APPROVED** [review]

**Comment by jackrr** [comment]
@rogervera friendly reminder to push and push --tags after doing your release on the alpha branch

**Comment by rogervera** [comment]
On it rn!

> @rogervera friendly reminder to push and push --tags after doing your release on the alpha branch

On it right now!

**Comment by jackrr** [comment]
Which i forgot to do :P

**Comment by jackrr** [comment]
@rogervera Wait

**Comment by rogervera** [comment]
> @rogervera Wait

Ah, just pushed.

**Pull request merged**
